name: Build Library with Gradle

on:
  push:
    branches:
      - main
      - feature/*
      - issue/*
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: sqlparser.jar
          path: build/libs/sqlparser.jar
      - name: Upload library test jar
        uses: actions/upload-artifact@v3
        with:
          name: sqlparser-test.jar
          path: build/libs/sqlparser-test.jar
